[project]
name = "juan-charfuelan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KrozFu", email = "carlosuefagh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
juan-charfuelan = "juan_charfuelan:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
